server:
  # 端口
  port: 8855
spring:
  application:
    name: zxdp
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zxdp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: AmberRedis
      database: 5 # 数据库索引，默认是0
      connect-timeout: 10000 # 连接超时时间，毫秒
      lettuce:
        pool:
          max-active: 8 # 最大连接数
          max-idle: 8 # 最大空闲连接数
          min-idle: 2 # 最小空闲连接数
          max-wait: 10000 # 最大等待时间，毫秒
# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # XML映射文件的路径（支持通配符）
    mapper-locations: classpath*:mapper/**/*.xml